#!C:\WinP\bd39\bucod\WPy64-3940\python-3.9.4.amd64\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
